version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root123
      POSTGRES_DB: classipy_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    env_file:
      - .env
    command: ["serve"]

  backend:
    build: .
    container_name: classipy_backend
    restart: always
    depends_on:
      - postgres
      - ollama
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: bash -c "python src/database/test_db_connection.py && uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  postgres_data:
  ollama_data:
