version: '3.8'

services:
  db:
    image: postgres:15
    container_name: classipy_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: classipy
    volumes:
      # Monta o script SQL para inicialização automática do banco
      - ./classipy_database.sql:/docker-entrypoint-initdb.d/init.sql
      # Volume para persistir os dados do banco
      - postgres_data:/var/lib/postgresql/data
    ports:
      # Expõe a porta do banco para o host (opcional, para debug)
      - "5433:5432"

  api:
    build: .
    container_name: classipy_api
    volumes:
      # Monta o código fonte para live-reloading durante o desenvolvimento
      - ./src:/app/src
    ports:
      - "8000:8000"
    environment:
      # A URL aponta para o serviço 'db', não para 'localhost'
      - DATABASE_URL=postgresql://postgres:root@db:5432/classipy
    depends_on:
      - db

volumes:
  postgres_data:
